<a href="https://colab.research.google.com/github/azhiif/PY_XTREME/blob/main/ashif_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing numpy 
import numpy as x 

#making a array1
array1 = x.array([ 
     [1, 2, 3, 5, 6],
    [2, 1, 5, 6, 7]
])

#making a array2
array2 = x.array([
    [2, 1, 5, 6, 7],
    [1, 2, 3, 5, 6]
])

#printing product of 2 array
print(array1*array2)

#print a new line
print()

#showing dimention of array1 
print("No. of dimensions of the array: ", array1.ndim)

##print a new line
print()

#showing shape of array1 
print("Shape of the array: ", array1.shape)

#print a new line
print()

#making some list of number
list1 = [1, 2, 3, 5, 6]
list2 = [3, 1, 4, 5, 1]

#combining 2 list as a single array named array3
array3 = x.array(
    [list1, list2]
)

#printing new made array3
print(array3)

##print a new line
print()

#making a array of zeros with dimension 3,4 and printing it
array4 = x.zeros((3, 4))
print(array4)


[[ 2  2 15 30 42]
 [ 2  2 15 30 42]]

No. of dimensions of the array:  2

Shape of the array:  (2, 5)

[[1 2 3 5 6]
 [3 1 4 5 1]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
