<a href="https://colab.research.google.com/github/HKRcodes/PY_XTREME/blob/main/pytorch/Adding_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.add(x,y)
print(z)

tensor([[0.5404, 0.5223],
        [0.9212, 0.0246]])
tensor([[0.7199, 0.0854],
        [0.9088, 0.7942]])
tensor([[1.2603, 0.6077],
        [1.8300, 0.8188]])
