<a href="https://colab.research.google.com/github/HKRcodes/PY_XTREME/blob/main/pytorch/Multiplying_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.mul(x,y)
print(z)

tensor([[0.5495, 0.4572],
        [0.0011, 0.8210]])
tensor([[0.1439, 0.3665],
        [0.5695, 0.3396]])
tensor([[0.0791, 0.1676],
        [0.0007, 0.2788]])
