<a href="https://colab.research.google.com/github/HKRcodes/PY_XTREME/blob/main/pytorch/Subtracting_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.sub(x,y)
print(z)

tensor([[0.0590, 0.1681],
        [0.1753, 0.0612]])
tensor([[0.5030, 0.6178],
        [0.8185, 0.4252]])
tensor([[-0.4440, -0.4496],
        [-0.6432, -0.3640]])
