<a href="https://colab.research.google.com/github/HKRcodes/PY_XTREME/blob/main/pytorch/Tensor_division.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.div(x,y)
print(z)

tensor([[0.2362, 0.9649],
        [0.4265, 0.1954]])
tensor([[0.5520, 0.8464],
        [0.5182, 0.2672]])
tensor([[0.4279, 1.1400],
        [0.8232, 0.7312]])
