<a href="https://colab.research.google.com/github/Annamjohn/PY_XTREME/blob/main/Numpy/matrixsubtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

# initialising numpy array
a=[]
n=int(input("Enter size of first matrix: "))
for i in range (n):                                       #temporary list to store the row
  for j in range (n): 
    x=int(input())                #add the input to row list
    a.append(x)                               #add the row to the list
A=np.asarray(a)

b=[]
m=int(input("Enter size of second matrix: "))
if n==m:
  for i in range (m):
    for j in range (m): 
      x=int(input())                #add the input to row list
      b.append(x)                               #add the row to the list
  B=np.asarray(b)



  print("Printing elements of first matrix")
  print(A)
  print("Printing elements of second matrix")
  print(B)

  # adding two matrix
  print("Subtraction of two matrix")
  print(np.subtract(A, B))


Enter size of first matrix: 2
1
5
1
3
Enter size of second matrix: 2
0
2
1
4
Printing elements of first matrix
[1 5 1 3]
Printing elements of second matrix
[0 2 1 4]
Subtraction of two matrix
[ 1  3  0 -1]
