<a href="https://colab.research.google.com/github/Annamjohn/PY_XTREME/blob/main/Numpy/matrixaddition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

# initialising numpy array
a=[]
n=int(input("Enter size of first matrix: "))
for i in range (n):                                       #temporary list to store the row
  for j in range (n): 
    x=int(input())                #add the input to row list
    a.append(x)                               #add the row to the list
A=np.asarray(a)

b=[]
m=int(input("Enter size of second matrix: "))
if n==m:
  for i in range (m):
    for j in range (m): 
      x=int(input())                #add the input to row list
      b.append(x)                               #add the row to the list
  B=np.asarray(b)



  print("Printing elements of first matrix")
  print(A)
  print("Printing elements of second matrix")
  print(B)

  # adding two matrix
  print("Addition of two matrix")
  print(np.add(A, B))


Enter size of first matrix: 2
1
2
3
4
Enter size of second matrix: 2
1
3
5
2
Printing elements of first matrix
[1 2 3 4]
Printing elements of second matrix
[1 3 5 2]
Addition of two matrix
[2 5 8 6]
